/* =========================================================
   Ultimate Luxury Sedan Comparison — Data & Translations
   ========================================================= */
"use strict";

/* ---------- Comparison categories (14) ---------- */
const CATEGORIES = [
  { id: "luxury",      icon: "💎", ar: "الفخامة",                 en: "Luxury" },
  { id: "comfort",     icon: "🛋️", ar: "راحة الركوب",             en: "Ride Comfort" },
  { id: "quietness",   icon: "🤫", ar: "هدوء المقصورة",           en: "Cabin Quietness" },
  { id: "interior",    icon: "🎨", ar: "التصميم الداخلي",          en: "Interior Design" },
  { id: "technology",  icon: "🖥️", ar: "التقنية",                 en: "Technology" },
  { id: "assistance",  icon: "🛡️", ar: "أنظمة مساعدة السائق",      en: "Driver Assistance" },
  { id: "rear",        icon: "👔", ar: "راحة الركاب الخلفيين",     en: "Rear Passenger Comfort" },
  { id: "prestige",    icon: "👑", ar: "الهيبة والمكانة",          en: "Prestige" },
  { id: "dynamics",    icon: "🏁", ar: "ديناميكية القيادة",        en: "Driving Dynamics" },
  { id: "build",       icon: "🔧", ar: "جودة الصنع",              en: "Build Quality" },
  { id: "value",       icon: "💰", ar: "القيمة مقابل السعر",       en: "Value" },
  { id: "reliability", icon: "⚙️", ar: "الموثوقية",               en: "Reliability" },
  { id: "presence",    icon: "🌟", ar: "الحضور على الطريق",        en: "Road Presence" },
  { id: "overall",     icon: "🏆", ar: "التجربة الشاملة",          en: "Overall Experience" },
];

/* ---------- Cars ----------
   scores[] follows CATEGORIES order, each 0–10.
   Totals are tuned so the final ranking is:
   1 Mercedes, 2 BMW, 3 Rolls-Royce, 4 Bentley, 5 Audi,
   6 Porsche, 7 Genesis, 8 Lexus, 9 Lucid, 10 Maserati. */
const CARS = [
  {
    id: "mercedes",
    en: "Mercedes-Benz S-Class",
    ar: "مرسيدس-بنز الفئة S",
    brandEn: "Mercedes-Benz", brandAr: "مرسيدس-بنز",
    colorEn: "Obsidian Black", colorAr: "أسود أوبسيديان",
    color: "#0b0b0f", colorLight: "#3a3a46", accent: "#d4af37",
    scores: [9.8, 9.9, 9.8, 9.7, 9.6, 9.7, 9.8, 9.5, 9.0, 9.6, 8.5, 9.0, 9.5, 9.9],
    specs: {
      engineEn: "4.0L V8 Biturbo + EQ Boost", engineAr: "V8 مزدوج التيربو 4.0 لتر + EQ Boost",
      hp: 496, torque: 700, topSpeed: 250, accel: "4.4", priceEn: "$135,000", priceAr: "135,000 دولار",
    },
    prosEn: ["Benchmark ride comfort and refinement", "E-Active Body Control glides over anything", "Rear cabin rivals a private jet"],
    prosAr: ["المعيار الأعلى في راحة الركوب والرقي", "نظام E-Active Body Control ينساب فوق كل شيء", "المقصورة الخلفية تنافس الطائرات الخاصة"],
    consEn: ["Options raise the price quickly", "Understated for some tastes"],
    consAr: ["الخيارات ترفع السعر بسرعة", "تصميم متحفظ لبعض الأذواق"],
  },
  {
    id: "bmw",
    en: "BMW 7 Series",
    ar: "بي إم دبليو الفئة السابعة",
    brandEn: "BMW", brandAr: "بي إم دبليو",
    colorEn: "Tanzanite Dark Blue", colorAr: "أزرق تنزانيت داكن",
    color: "#16264c", colorLight: "#3a5a94", accent: "#8ea9d8",
    scores: [9.5, 9.6, 9.5, 9.4, 9.8, 9.6, 9.6, 9.0, 9.5, 9.4, 8.7, 9.0, 9.3, 9.5],
    specs: {
      engineEn: "4.4L V8 TwinPower Turbo", engineAr: "V8 مزدوج التيربو 4.4 لتر",
      hp: 536, torque: 750, topSpeed: 250, accel: "4.2", priceEn: "$127,000", priceAr: "127,000 دولار",
    },
    prosEn: ["Theatre Screen wows every passenger", "Sharpest tech in the class", "Surprisingly agile for its size"],
    prosAr: ["الشاشة السينمائية تبهر كل الركاب", "أفضل تقنيات في الفئة", "رشاقة مدهشة لحجمها"],
    consEn: ["Polarizing front-end design", "Complex menus take learning"],
    consAr: ["تصميم أمامي مثير للجدل", "قوائم معقدة تحتاج وقتاً للتعلم"],
  },
  {
    id: "audi",
    en: "Audi A8",
    ar: "أودي A8",
    brandEn: "Audi", brandAr: "أودي",
    colorEn: "Floret Silver", colorAr: "فضي فلوريت",
    color: "#c8ccd4", colorLight: "#eef0f4", accent: "#9aa2ae",
    scores: [9.0, 9.2, 9.4, 9.1, 9.3, 9.2, 9.0, 8.6, 8.8, 9.2, 8.8, 8.9, 8.7, 8.9],
    specs: {
      engineEn: "4.0L V8 TFSI", engineAr: "V8 تيربو 4.0 لتر TFSI",
      hp: 453, torque: 660, topSpeed: 250, accel: "4.6", priceEn: "$90,000", priceAr: "90,000 دولار",
    },
    prosEn: ["Impeccable cabin build quality", "Quattro all-weather confidence", "Discreet, elegant presence"],
    prosAr: ["جودة صنع داخلية لا تشوبها شائبة", "ثقة نظام كواترو في كل الظروف", "حضور أنيق وراقٍ بلا تكلّف"],
    consEn: ["Ageing platform", "Less rear-seat drama than rivals"],
    consAr: ["منصة بدأت تتقادم", "مقاعد خلفية أقل إبهاراً من المنافسين"],
  },
  {
    id: "lexus",
    en: "Lexus LS",
    ar: "لكزس LS",
    brandEn: "Lexus", brandAr: "لكزس",
    colorEn: "Sonic White", colorAr: "أبيض سونيك",
    color: "#f2f3f5", colorLight: "#ffffff", accent: "#b9bec7",
    scores: [8.8, 9.1, 9.3, 8.8, 8.4, 8.8, 8.9, 8.0, 8.3, 9.4, 8.9, 10.0, 8.3, 8.6],
    specs: {
      engineEn: "3.5L V6 Twin-Turbo", engineAr: "V6 مزدوج التيربو 3.5 لتر",
      hp: 416, torque: 600, topSpeed: 250, accel: "5.0", priceEn: "$80,000", priceAr: "80,000 دولار",
    },
    prosEn: ["Legendary reliability", "Takumi hand-crafted details", "Serene, whisper-quiet cabin"],
    prosAr: ["موثوقية أسطورية", "تفاصيل حرفية يدوية من فناني تاكومي", "مقصورة هادئة كالهمس"],
    consEn: ["Infotainment behind the Germans", "Least prestigious badge here"],
    consAr: ["نظام ترفيهي خلف الألمان", "شارة أقل هيبة في هذه المجموعة"],
  },
  {
    id: "porsche",
    en: "Porsche Panamera",
    ar: "بورشه باناميرا",
    brandEn: "Porsche", brandAr: "بورشه",
    colorEn: "Volcano Grey", colorAr: "رمادي بركاني",
    color: "#6b6f76", colorLight: "#a2a7b0", accent: "#c33",
    scores: [8.9, 8.6, 8.7, 9.0, 9.2, 9.0, 8.4, 9.0, 10.0, 9.3, 8.0, 8.8, 9.2, 9.2],
    specs: {
      engineEn: "4.0L V8 Turbo E-Hybrid", engineAr: "V8 تيربو هجين 4.0 لتر",
      hp: 680, torque: 930, topSpeed: 315, accel: "3.2", priceEn: "$190,000", priceAr: "190,000 دولار",
    },
    prosEn: ["Sports-car dynamics in a sedan", "Monstrous hybrid performance", "Driver-first cockpit"],
    prosAr: ["ديناميكية سيارة رياضية في هيكل سيدان", "أداء هجين وحشي", "مقصورة مصممة حول السائق"],
    consEn: ["Firmer ride than pure limos", "Rear space merely good"],
    consAr: ["ركوب أكثر صلابة من الليموزينات الخالصة", "مساحة خلفية جيدة فقط"],
  },
  {
    id: "genesis",
    en: "Genesis G90",
    ar: "جينيسيس G90",
    brandEn: "Genesis", brandAr: "جينيسيس",
    colorEn: "Vik Black", colorAr: "أسود فيك",
    color: "#101014", colorLight: "#3c3c46", accent: "#a8763e",
    scores: [9.1, 9.0, 9.2, 9.0, 9.0, 8.9, 9.2, 7.8, 8.2, 9.0, 9.8, 9.0, 8.6, 8.8],
    specs: {
      engineEn: "3.5L V6 Turbo e-Supercharger", engineAr: "V6 تيربو مع شاحن كهربائي 3.5 لتر",
      hp: 409, torque: 549, topSpeed: 250, accel: "5.1", priceEn: "$90,000", priceAr: "90,000 دولار",
    },
    prosEn: ["Astonishing value for money", "Flagship features as standard", "Beautiful restrained design"],
    prosAr: ["قيمة مذهلة مقابل السعر", "تجهيزات الفئة الأولى قياسية", "تصميم جميل ورصين"],
    consEn: ["Badge still building prestige", "No performance flagship"],
    consAr: ["الشارة ما زالت تبني مكانتها", "لا توجد نسخة أداء عليا"],
  },
  {
    id: "maserati",
    en: "Maserati Quattroporte",
    ar: "مازيراتي كواتروبورتي",
    brandEn: "Maserati", brandAr: "مازيراتي",
    colorEn: "Rosso Folgore Dark Red", colorAr: "أحمر داكن روسو فولغوري",
    color: "#6e1423", colorLight: "#a2333f", accent: "#123a5f",
    scores: [8.7, 8.2, 8.1, 9.2, 7.8, 7.9, 8.0, 8.8, 9.2, 8.0, 7.2, 7.5, 9.4, 8.4],
    specs: {
      engineEn: "3.8L V8 Twin-Turbo (Trofeo)", engineAr: "V8 مزدوج التيربو 3.8 لتر (تروفيو)",
      hp: 572, torque: 730, topSpeed: 326, accel: "4.5", priceEn: "$150,000", priceAr: "150,000 دولار",
    },
    prosEn: ["Operatic Italian V8 soundtrack", "Head-turning drama and style", "Genuine motorsport pedigree"],
    prosAr: ["صوت V8 إيطالي أوبرالي", "إطلالة وأناقة تخطف الأنظار", "نسب رياضي أصيل"],
    consEn: ["Trails on technology", "Running costs and reliability"],
    consAr: ["متأخرة في التقنيات", "تكاليف تشغيل وموثوقية أقل"],
  },
  {
    id: "bentley",
    en: "Bentley Flying Spur",
    ar: "بنتلي فلاينج سبير",
    brandEn: "Bentley", brandAr: "بنتلي",
    colorEn: "British Racing Green", colorAr: "أخضر السباقات البريطاني",
    color: "#0b3d2e", colorLight: "#1e6a50", accent: "#d4af37",
    scores: [9.9, 9.6, 9.6, 9.8, 8.6, 8.5, 9.5, 9.8, 8.9, 9.8, 6.9, 8.7, 9.8, 9.4],
    specs: {
      engineEn: "6.0L W12 Twin-Turbo", engineAr: "W12 مزدوج التيربو 6.0 لتر",
      hp: 626, torque: 900, topSpeed: 333, accel: "3.8", priceEn: "$250,000", priceAr: "250,000 دولار",
    },
    prosEn: ["Handcrafted British opulence", "W12 pace of a supercar", "Interior is rolling art"],
    prosAr: ["بذخ بريطاني مصنوع يدوياً", "سرعة سيارة خارقة بمحرك W12", "الداخلية تحفة فنية متحركة"],
    consEn: ["Stratospheric price", "Thirsty W12"],
    consAr: ["سعر فلكي", "استهلاك وقود مرتفع"],
  },
  {
    id: "rolls",
    en: "Rolls-Royce Ghost",
    ar: "رولز-رويس جوست",
    brandEn: "Rolls-Royce", brandAr: "رولز-رويس",
    colorEn: "Arctic White", colorAr: "أبيض قطبي",
    color: "#f7f7f4", colorLight: "#ffffff", accent: "#7d6a3a",
    scores: [10.0, 9.8, 9.9, 9.9, 8.5, 8.6, 9.9, 10.0, 8.4, 9.9, 6.5, 8.8, 10.0, 9.6],
    specs: {
      engineEn: "6.75L V12 Twin-Turbo", engineAr: "V12 مزدوج التيربو 6.75 لتر",
      hp: 563, torque: 850, topSpeed: 250, accel: "4.8", priceEn: "$350,000", priceAr: "350,000 دولار",
    },
    prosEn: ["Magic Carpet Ride serenity", "Unmatched aura and presence", "Bespoke craftsmanship"],
    prosAr: ["انسيابية 'البساط السحري'", "هالة وحضور لا يُضاهيان", "حرفية مخصصة حسب الطلب"],
    consEn: ["Price of a small villa", "Too grand for daily anonymity"],
    consAr: ["سعر فيلا صغيرة", "أفخم من أن تمر دون أن يلاحظها أحد"],
  },
  {
    id: "lucid",
    en: "Lucid Air Sapphire",
    ar: "لوسيد إير سافاير",
    brandEn: "Lucid", brandAr: "لوسيد",
    colorEn: "Sapphire Blue", colorAr: "أزرق ياقوتي",
    color: "#1b4a8a", colorLight: "#3f74bd", accent: "#c9d6ea",
    scores: [8.5, 8.8, 9.0, 8.7, 10.0, 9.3, 8.6, 7.5, 9.4, 8.6, 8.2, 8.2, 8.5, 8.8],
    specs: {
      engineEn: "Tri-Motor Electric", engineAr: "كهربائي بثلاثة محركات",
      hp: 1234, torque: 1940, topSpeed: 330, accel: "2.0", priceEn: "$249,000", priceAr: "249,000 دولار",
    },
    prosEn: ["1,234 hp hypercar acceleration", "Class-leading EV range and tech", "Futuristic minimalist cabin"],
    prosAr: ["تسارع خارق بقوة 1,234 حصاناً", "مدى كهربائي وتقنيات تتصدر الفئة", "مقصورة مستقبلية بسيطة"],
    consEn: ["Young brand, small network", "Firm ride in Sapphire tune"],
    consAr: ["علامة ناشئة وشبكة خدمة محدودة", "ركوب صلب في إعداد سافاير"],
  },
];

/* Podium order requirement: Mercedes center, BMW left, Rolls right. */
const FINAL_RANK_IDS = [
  "mercedes", "bmw", "rolls", "bentley", "audi",
  "porsche", "genesis", "lexus", "lucid", "maserati",
];

/* ---------- UI translations ---------- */
const I18N = {
  ar: {
    dir: "rtl",
    langButton: "English",
    brand: "المقارنة المطلقة",
    loading: "جارٍ تجهيز التجربة الفاخرة…",
    heroKicker: "عرض حصري بأسلوب إطلاق عالمي",
    heroTitle: "المقارنة المطلقة لسيارات السيدان الفاخرة",
    heroSubtitle: "عشر سيارات أسطورية. أربع عشرة معركة. عرش واحد فقط.",
    compareBtn: "قارن السيارات",
    scrollHint: "اكتشف المتنافسات",
    contendersTitle: "المتنافسات على العرش",
    contendersSub: "اضغط على أي سيارة لعرض مواصفاتها الكاملة",
    arenaTitle: "حلبة المقارنة",
    liveStandings: "الترتيب المباشر",
    category: "الفئة",
    of: "من",
    points: "نقطة",
    skip: "تخطّي إلى النتيجة ⏭",
    finalTitle: "النتيجة النهائية",
    suspense: "لحظة الحسم…",
    revealing: "الكشف عن المراكز",
    championTitle: "ملكة سيارات السيدان الفاخرة",
    championSubtitle: "مرسيدس-بنز الفئة S تبقى المعيار الأعلى للفخامة التنفيذية.",
    replay: "🔁 إعادة المقارنة",
    fullRanking: "الترتيب الكامل",
    totalScore: "النقاط الكلية",
    rank: "المركز",
    specs: "المواصفات",
    horsepower: "القوة",
    hpUnit: "حصان",
    torque: "عزم الدوران",
    nmUnit: "نيوتن.متر",
    engine: "المحرك",
    topSpeed: "السرعة القصوى",
    kmh: "كم/س",
    accel: "التسارع 0–100 كم/س",
    sec: "ثانية",
    price: "السعر التقريبي",
    pros: "المميزات",
    cons: "العيوب",
    luxuryScore: "الفخامة",
    techScore: "التقنية",
    overallScore: "التقييم العام",
    close: "إغلاق",
    winnerTag: "أفضل الفئة",
    footer: "تجربة رقمية فاخرة · صُممت بشغف",
    place: ["الأول", "الثاني", "الثالث", "الرابع", "الخامس", "السادس", "السابع", "الثامن", "التاسع", "العاشر"],
    medals: ["🥇", "🥈", "🥉"],
  },
  en: {
    dir: "ltr",
    langButton: "العربية",
    brand: "THE ULTIMATE COMPARISON",
    loading: "Preparing the luxury experience…",
    heroKicker: "An exclusive keynote-style showcase",
    heroTitle: "Ultimate Luxury Sedan Comparison",
    heroSubtitle: "Ten legendary sedans. Fourteen battles. Only one throne.",
    compareBtn: "Compare Cars",
    scrollHint: "Meet the contenders",
    contendersTitle: "Contenders for the Throne",
    contendersSub: "Click any car to reveal its full specification",
    arenaTitle: "The Comparison Arena",
    liveStandings: "Live Standings",
    category: "Category",
    of: "of",
    points: "pts",
    skip: "Skip to results ⏭",
    finalTitle: "The Final Verdict",
    suspense: "The moment of truth…",
    revealing: "Revealing the ranks",
    championTitle: "The Queen of Luxury Sedans",
    championSubtitle: "Mercedes-Benz S-Class remains the benchmark for executive luxury.",
    replay: "🔁 Replay Comparison",
    fullRanking: "Full Ranking",
    totalScore: "Total Score",
    rank: "Rank",
    specs: "Specifications",
    horsepower: "Horsepower",
    hpUnit: "hp",
    torque: "Torque",
    nmUnit: "Nm",
    engine: "Engine",
    topSpeed: "Top Speed",
    kmh: "km/h",
    accel: "0–100 km/h",
    sec: "s",
    price: "Approx. Price",
    pros: "Pros",
    cons: "Cons",
    luxuryScore: "Luxury",
    techScore: "Technology",
    overallScore: "Overall",
    close: "Close",
    winnerTag: "Best in class",
    footer: "A premium digital experience · Crafted with passion",
    place: ["1st", "2nd", "3rd", "4th", "5th", "6th", "7th", "8th", "9th", "10th"],
    medals: ["🥇", "🥈", "🥉"],
  },
};
